# Generated by Django 3.1.7 on 2021-03-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('lid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('landmark_name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('logitude', models.CharField(max_length=200, null=True)),
                ('facility', models.CharField(max_length=200, null=True)),
                ('park', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('tel', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'landmarks',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=39, null=True)),
                ('menu_name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=30, null=True)),
                ('sid', models.CharField(max_length=30, null=True)),
                ('num', models.CharField(max_length=30, null=True)),
                ('total_score', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('reg_time', models.TextField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('logitude', models.CharField(max_length=100, null=True)),
                ('review_cnt', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ZzimLandCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=30, null=True)),
                ('lid1', models.CharField(max_length=30, null=True)),
                ('lid2', models.CharField(max_length=30, null=True)),
                ('lid3', models.CharField(max_length=30, null=True)),
                ('lid4', models.CharField(max_length=30, null=True)),
                ('isSaved', models.CharField(max_length=30, null=True)),
                ('savedDate', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'zzimLandCourses',
            },
        ),
        migrations.CreateModel(
            name='ZzimStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=30, null=True)),
                ('sid', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'zzimStores',
            },
        ),
        migrations.CreateModel(
            name='ZzimStoreCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=30, null=True)),
                ('sidB', models.CharField(max_length=30, null=True)),
                ('isSavedB', models.CharField(max_length=30, null=True)),
                ('sidL', models.CharField(max_length=30, null=True)),
                ('isSavedL', models.CharField(max_length=30, null=True)),
                ('sidD', models.CharField(max_length=30, null=True)),
                ('isSavedD', models.CharField(max_length=30, null=True)),
                ('savedDate', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'zzimStoreCourses',
            },
        ),
    ]
