# Generated by Django 3.1.7 on 2021-03-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('lid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('landmark_name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('logitude', models.CharField(max_length=200, null=True)),
                ('facility', models.CharField(max_length=200, null=True)),
                ('park', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('tel', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'landmarks',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('logitude', models.CharField(max_length=100, null=True)),
                ('review_cnt', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ZzimStoreCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSavedB', models.CharField(max_length=100, null=True)),
                ('isSavedL', models.CharField(max_length=100, null=True)),
                ('isSavedD', models.CharField(max_length=100, null=True)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('sidB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidB', to='recommendroad.store')),
                ('sidD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidD', to='recommendroad.store')),
                ('sidL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidL', to='recommendroad.store')),
            ],
            options={
                'db_table': 'zzimStoreCourses',
            },
        ),
        migrations.CreateModel(
            name='ZzimStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendroad.store')),
            ],
            options={
                'db_table': 'zzimStores',
            },
        ),
        migrations.CreateModel(
            name='ZzimLandCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSaved', models.CharField(max_length=100, null=True)),
                ('savedDate', models.CharField(max_length=200, null=True)),
                ('lid1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lid1', to='recommendroad.landmark')),
                ('lid2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lid2', to='recommendroad.landmark')),
                ('lid3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lid3', to='recommendroad.landmark')),
                ('lid4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lid4', to='recommendroad.landmark')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'zzimLandCourses',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('total_score', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('reg_time', models.TextField()),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendroad.store')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendroad.store')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
