# Generated by Django 3.1.7 on 2021-03-30 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendroad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=50, null=True)),
                ('t2', models.CharField(max_length=50, null=True)),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'rScoreTables',
            },
        ),
        migrations.AlterField(
            model_name='zzimlandcourse',
            name='savedDate',
            field=models.CharField(default=datetime.datetime(2021, 3, 30, 21, 7, 46, 254184), max_length=100, null=True),
        ),
    ]
