# Generated by Django 3.1.7 on 2021-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
