# Generated by Django 2.2.7 on 2021-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
            ],
        ),
    ]
